---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab-staging
  namespace: gitlab
spec:
  chart:
    name: gitlab
    repository: https://charts.gitlab.io
    version: 5.6.3
  releaseName: gitlab-staging
  values:
    certmanager:
      install: false
    gitlab:
      gitaly:
        nodeSelector:
          spack.io/node-pool: gitlab
      gitlab-exporter:
        nodeSelector:
          spack.io/node-pool: gitlab
      gitlab-shell:
        nodeSelector:
          spack.io/node-pool: gitlab
      ingress:
        tls:
          enabled: true
      migrations:
        nodeSelector:
          spack.io/node-pool: gitlab
      sidekiq:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/spack/gitlab-sidekiq
          tag: v14.6.3
        nodeSelector:
          spack.io/node-pool: gitlab
      toolbox:
        antiAffinityLabels:
          matchLabels:
            app: gitaly
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/spack/gitlab-toolbox
          tag: v14.6.3
        nodeSelector:
          spack.io/node-pool: gitlab
        replicas: 8
      webservice:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/spack/gitlab-webservice
          tag: v14.6.3
        ingress:
          enabled: true
          tls:
            enabled: true
            secretName: tls-gitlab-staging-webservice
        maxReplicas: 3
        minReplicas: 1
        nodeSelector:
          spack.io/node-pool: gitlab
        resources:
          limits:
            cpu: 1500m
            memory: 2.5G
          requests:
            cpu: 300m
            memory: 1.5G
    gitlab-runner:
      install: false
    global:
      antiAffinity: hard
      common:
        labels: {}
      edition: ee
      email:
        from: admin@gitlab.staging.spack.io
        reply_to: noreply@gitlab.staging.spack.io
      gitlab:
        license: {}
      hosts:
        domain: staging.spack.io
        gitlab:
          name: gitlab.staging.spack.io
        https: true
        minio:
          name: minio.gitlab.staging.spack.io
        registry:
          name: registry.gitlab.staging.spack.io
        smartcard:
          enabled: false
      ingress:
        class: nginx
        configureCertmanager: false
      initialRootPassword: {}
      operator:
        enabled: false
      psql:
        connectTimeout: null
        database: gitlabhq_production
        password:
          key: postgres-password
          secret: gitlab-staging-secrets
        port: 5432
        username: gitlab
      smtp:
        address: email-smtp.us-east-1.amazonaws.com
        enabled: true
        password:
          secret: smtp-password
        port: 465
        tls: true
        user_name: AKIAYSCIUVA2HA4WTV6O
    grafana:
      enabled: false
    minio:
      ingress:
        tls:
          secretName: tls-gitlab-staging-minio
      nodeSelector:
        spack.io/node-pool: gitlab
      persistence:
        size: 10Gi
    nginx-ingress:
      enabled: false
    nodeSelector:
      spack.io/node-pool: gitlab
    postgresql:
      install: false
    prometheus:
      install: false
    registry:
      ingress:
        tls:
          secretName: tls-gitlab-staging-registry
      nodeSelector:
        spack.io/node-pool: gitlab
  valuesFrom:
  - secretKeyRef:
      key: values.yaml
      name: gitlab-staging-secrets
      namespace: gitlab
      optional: false
