---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: runner-staging
  namespace: gitlab
spec:
  chart:
    name: gitlab-runner
    repository: https://charts.gitlab.io
    version: 0.25.0
  releaseName: runner-staging
  values:
    checkInterval: 1
    concurrent: 3
    gitlabUrl: https://gitlab.staging.spack.io/
    image: gitlab/gitlab-runner:alpine-v13.8.0
    imagePullPolicy: IfNotPresent
    metrics:
      enabled: true
    nodeSelector:
      spack.io/node-pool: base
    rbac:
      serviceAccountName: runner
    runners:
      builds: {}
      cache: {}
      config: "[[runners]]\n  environment = [\"FF_GITLAB_REGISTRY_HELPER_IMAGE=1\"\
        ]\n"
      helpers: {}
      image: busybox:1.32.0
      imagePullPolicy: if-not-present
      locked: false
      namespace: gitlab
      nodeSelector:
        spack.io/node-pool: glr-xlarge-pub
      outputLimit: 4096
      pollTimeout: 30
      privileged: false
      requestConcurrency: 3
      runUntagged: false
      secret: gitlab-staging-gitlab-runner-secret
      serviceAccountName: runner
      services: {}
      tags: x86_64,avx,avx2,avx512,staging,public,aws,spack
    terminationGracePeriodSeconds: 300
    unregisterRunners: true
