---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-postgres
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase-postgres
  template:
    metadata:
      labels:
        app: metabase-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: metabase-postgresql-password
        envFrom:
        - configMapRef:
            name: postgres-config
        image: postgres:14.0
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: metabase-postgresql
