---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slack-spack-io
    svc: web
  name: slack-spack-io
  namespace: spack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slack-spack-io
      svc: web
  template:
    metadata:
      labels:
        app: slack-spack-io
        svc: web
    spec:
      containers:
      - env:
        - name: SLACK_SUBDOMAIN
          value: spackpm
        - name: SLACKIN_ANALYTICS
          value: UA-101208306-3
        - name: SLACKIN_PORT
          value: '80'
        - name: SLACKIN_COC
          value: https://github.com/spack/spack/blob/develop/.github/CODE_OF_CONDUCT.md
        - name: SLACK_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: slack_api_token
              name: spack-slackin-credentials
        - name: RECAPTCHA_SITEKEY
          valueFrom:
            secretKeyRef:
              key: google_captcha_sitekey
              name: spack-slackin-credentials
        - name: RECAPTCHA_SECRET
          valueFrom:
            secretKeyRef:
              key: google_captcha_secret
              name: spack-slackin-credentials
        image: spack/slackin-extended:latest
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 20m
            memory: 65M
      nodeSelector:
        spack.io/node-pool: base
