---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluent-bit-logging
    kubernetes.io/cluster-service: 'true'
    version: v1
  name: fluent-bit
  namespace: logging
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/v1/metrics/prometheus
        prometheus.io/port: '2020'
        prometheus.io/scrape: 'true'
      labels:
        k8s-app: fluent-bit-logging
        kubernetes.io/cluster-service: 'true'
        version: v1
    spec:
      containers:
      - image: amazon/aws-for-fluent-bit:2.27.0
        imagePullPolicy: Always
        name: fluent-bit
        ports:
        - containerPort: 2020
        resources:
          requests:
            cpu: 150m
            memory: 500M
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluent-bit/etc/
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
      - name: fluent-bit-config
        projected:
          sources:
          - configMap:
              name: fluent-bit-config
          - secret:
              name: fluent-bit-secrets
