---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - env:
        - name: MB_DB_PASS
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: metabase-postgresql-password
        envFrom:
        - configMapRef:
            name: metabase-config
        image: metabase/metabase:v0.41.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
        name: metabase
        ports:
        - containerPort: 3000
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
