---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    fluxcd.io/ignore: 'true'
  name: job-create-ro-gitlab-postgres-user
  namespace: gitlab
spec:
  template:
    metadata:
      labels:
        job: create-ro-gitlab-postgres-user
    spec:
      containers:
      - args:
        - psql -c " DO \$\$ BEGIN CREATE ROLE gitlab_ro_user; EXCEPTION WHEN duplicate_object
          THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE; END \$\$;
          ALTER ROLE gitlab_ro_user LOGIN PASSWORD '$RO_PGPASSWORD'; GRANT CONNECT
          ON DATABASE $PGDATABASE TO gitlab_ro_user; GRANT SELECT ON ALL TABLES IN
          SCHEMA public TO gitlab_ro_user; ALTER DEFAULT PRIVILEGES IN SCHEMA public
          GRANT SELECT ON TABLES TO gitlab_ro_user;";
        command:
        - /bin/bash
        - -c
        env:
        - name: PGUSER
          value: postgres
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              key: gitlab-postgresql-host
              name: gitlab-postgresql-secrets
        - name: PGDATABASE
          value: gitlabhq_production
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: gitlab-postgresql-password
              name: gitlab-postgresql-secrets
        - name: RO_PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-gitlab-ro-user-password
              name: gitlab-ro-postgresql-password
        image: docker.io/bitnami/postgresql:11.9.0
        name: create-ro-gitlab-postgres-user-container
      restartPolicy: Never
      securityContext:
        fsGroup: 1001
