---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rotate-gitlab-aws-access-keys
  namespace: custom
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: gitlab-token
                  name: rotate-keys
            image: ghcr.io/spack/ci-key-rotate:0.0.2
            imagePullPolicy: IfNotPresent
            name: rotate-gitlab-aws-access-keys
          nodeSelector:
            spack.io/node-pool: base
          restartPolicy: Never
          serviceAccountName: rotate-keys
  schedule: 0 */12 * * *
