---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clear-admin-keys
  namespace: custom
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: zackgalbreath/spack-clear-admin-keys:0.0.1
            imagePullPolicy: IfNotPresent
            name: clear-admin-keys
          nodeSelector:
            spack.io/node-pool: base
          restartPolicy: Never
          serviceAccountName: clear-admin-keys
  schedule: 0 0 10 */2 *
