---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metabase-postgres
  name: metabase-postgres
  namespace: monitoring
spec:
  ports:
  - port: 5432
  selector:
    app: metabase-postgres
  type: ClusterIP
