---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: gitlab
stringData:
  postgres-password: password
  values.yaml: "global:\n  psql:\n    host: host.rds.example.com # fake hostname\n"
