---
apiVersion: v1
data:
  apiVersion: helm.fluxcd.io/v1
  kind: HelmRelease
  name: gitlab
  patch: "- op: replace\n  path: /metadata/name\n  value: gitlab-{ENV}\n- op: replace\n\
    \  path: /spec/releaseName\n  value: gitlab-{ENV}\n- op: replace\n  path: /spec/chart/version\n\
    \  value: 5.4.1  # gitlab@14.4.1\n- op: replace\n  path: /spec/values/global/hosts/domain\n\
    \  value: \"{ENV}.spack.io\"\n- op: replace\n  path: /spec/values/global/hosts/gitlab/name\n\
    \  value: gitlab.{ENV}.spack.io\n- op: replace\n  path: /spec/values/global/hosts/minio/name\n\
    \  value: minio.gitlab.{ENV}.spack.io\n- op: replace\n  path: /spec/values/global/hosts/registry/name\n\
    \  value: registry.gitlab.{ENV}.spack.io\n- op: remove\n  path: /spec/values/global/hosts/ssh\n\
    - op: replace\n  path: /spec/values/global/email/from\n  value: admin@gitlab.{ENV}.spack.io\n\
    - op: replace\n  path: /spec/values/global/email/reply_to\n  value: noreply@gitlab.{ENV}.spack.io\n\
    - op: remove\n  path: /spec/values/global/psql\n- op: remove\n  path: /spec/values/global/redis\n\
    - op: remove\n  path: /spec/values/global/minio\n- op: remove\n  path: /spec/values/global/grafana\n\
    - op: remove\n  path: /spec/values/global/appConfig\n- op: replace\n  path: /spec/values/minio/ingress/tls/secretName\n\
    \  value: tls-gitlab-{ENV}-minio\n- op: replace\n  path: /spec/values/minio/persistence/size\n\
    \  value: 10Gi\n- op: replace\n  path: /spec/values/registry/ingress/tls/secretName\n\
    \  value: tls-gitlab-{ENV}-registry\n- op: add\n  path: /spec/values\n  value:\n\
    \    grafana:\n      enabled: false\n- op: replace\n  path: /spec/values/gitlab/webservice/ingress/tls/secretName\n\
    \  value: tls-gitlab-{ENV}-webservice\n- op: replace\n  path: /spec/values/gitlab/webservice/image/tag\n\
    \  value: v14.4.1\n- op: replace\n  path: /spec/values/gitlab/webservice/minReplicas\n\
    \  value: 1\n- op: replace\n  path: /spec/values/gitlab/webservice/maxReplicas\n\
    \  value: 3\n- op: remove\n  path: /spec/values/gitlab/gitlab-shell/service\n\
    - op: replace\n  path: /spec/values/gitlab/sidekiq/image/tag\n  value: v14.4.1\n\
    - op: replace\n  path: /spec/values/gitlab/task-runner/image/tag\n  value: v14.4.1\n\
    - op: replace\n  path: /spec/values/gitlab/task-runner/replicas\n  value: 3\n"
kind: ConfigMap
metadata:
  annotations:
    cd.spack.io/staged-resource: '1'
  name: gitlab-staging-patch
  namespace: gitlab
