---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metabase
  name: metabase
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: metabase
  type: ClusterIP
