---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spackbotdev-spack-io
    svc: web
  name: spackbotdev-spack-io
  namespace: spack
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: spackbotdev-spack-io
    svc: web
  type: ClusterIP
