---
apiVersion: v1
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: metabase
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  labels:
    app: postgres
  name: postgres-config
  namespace: monitoring
