---
apiVersion: v1
data:
  id_rsa: '# result of:

    # $(echo -n cat id_spackbot) | base64 | tr -d ''\n''

    '
  id_rsa.pub: '# result of:

    # $(echo -n cat id_spackbot.pub) | base64 | tr -d ''\n''

    '
kind: Secret
metadata:
  annotations:
    fluxcd.io/ignore: 'true'
  labels:
    app: spackbot-spack-io
    svc: web
  name: spack-bot-idrsa
  namespace: spack
