---
apiVersion: v1
data:
  apiVersion: helm.fluxcd.io/v1
  kind: HelmRelease
  name: runner-xlarge-x86-pub
  patch: "- op: replace\n  path: /metadata/name\n  value: runner-{ENV}\n- op: replace\n\
    \  path: /spec/chart/version\n  value: \"0.37.1\"  # bleeding edge\n- op: replace\n\
    \  path: /spec/releaseName\n  value: runner-{ENV}\n- op: replace\n  path: /spec/values/gitlabUrl\n\
    \  value: \"https://gitlab.{ENV}.spack.io/\"\n- op: replace\n  path: /spec/values/terminationGracePeriodSeconds\n\
    \  value: 300  # five minutes\n- op: replace\n  path: /spec/values/concurrent\n\
    \  value: 3\n- op: replace\n  path: /spec/values/checkInterval\n  value: 1\n-\
    \ op: replace\n  path: /spec/values/runners/requestConcurrency\n  value: 3\n-\
    \ op: replace\n  path: /spec/values/runners/tags\n  value: \"x86_64,avx,avx2,avx512,{ENV},public,aws,spack\"\
    \n- op: replace\n  path: /spec/values/runners/secret\n  value: gitlab-{ENV}-gitlab-runner-secret\n\
    - op: replace\n  path: /spec/values/runners/namespace\n  value: gitlab\n"
kind: ConfigMap
metadata:
  annotations:
    cd.spack.io/staged-resource: '1'
  name: runner-staging-patch
  namespace: gitlab
