---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus
  namespace: monitoring
spec:
  dnsNames:
  - prometheus.spack.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-prometheus-webservice
