---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  dnsNames:
  - alertmanager.spack.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-alertmanager-webservice
