---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-metabase
  namespace: monitoring
spec:
  commonName: metabase.spack.io
  dnsNames:
  - metabase.spack.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-metabase
