---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    name: gitlab
    repository: https://charts.gitlab.io
    version: 5.6.3
  releaseName: gitlab
  values:
    certmanager:
      install: false
    gitlab:
      gitaly:
        nodeSelector:
          spack.io/node-pool: gitlab
      gitlab-exporter:
        nodeSelector:
          spack.io/node-pool: gitlab
      gitlab-shell:
        nodeSelector:
          spack.io/node-pool: gitlab
        service:
          type: LoadBalancer
      ingress:
        tls:
          enabled: true
      migrations:
        nodeSelector:
          spack.io/node-pool: gitlab
      sidekiq:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/spack/gitlab-sidekiq
          tag: v14.6.3
        nodeSelector:
          spack.io/node-pool: gitlab
      toolbox:
        antiAffinityLabels:
          matchLabels:
            app: gitaly
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/spack/gitlab-toolbox
          tag: v14.6.3
        nodeSelector:
          spack.io/node-pool: gitlab
        replicas: 8
      webservice:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/spack/gitlab-webservice
          tag: v14.6.3
        ingress:
          enabled: true
          tls:
            enabled: true
            secretName: tls-gitlab-webservice
        maxReplicas: 16
        minReplicas: 4
        nodeSelector:
          spack.io/node-pool: gitlab
        resources:
          limits:
            cpu: 1500m
            memory: 3.5G
          requests:
            cpu: 300m
            memory: 2.5G
    gitlab-runner:
      install: false
    global:
      antiAffinity: hard
      appConfig:
        smartcard:
          enabled: false
      common:
        labels: {}
      edition: ee
      email:
        from: admin@gitlab.spack.io
        reply_to: noreply@gitlab.spack.io
      gitlab:
        license: {}
      grafana:
        enabled: false
      hosts:
        domain: spack.io
        gitlab:
          name: gitlab.spack.io
        https: true
        minio:
          name: minio.gitlab.spack.io
        registry:
          name: registry.gitlab.spack.io
        smartcard:
          enabled: false
        ssh: ssh.gitlab.spack.io
      ingress:
        class: nginx
        configureCertmanager: false
      initialRootPassword: {}
      minio:
        enabled: true
      operator:
        enabled: false
      psql:
        connectTimeout: null
        database: gitlabhq_production
        password:
          key: postgres-password
          secret: gitlab-secrets
        port: 5432
        username: gitlab
      redis:
        password:
          enabled: true
      smtp:
        address: email-smtp.us-east-1.amazonaws.com
        enabled: true
        password:
          secret: smtp-password
        port: 465
        tls: true
        user_name: AKIAYSCIUVA2HA4WTV6O
    minio:
      ingress:
        tls:
          secretName: tls-gitlab-minio
      nodeSelector:
        spack.io/node-pool: gitlab
      persistence:
        size: 1000Gi
      resources:
        requests:
          cpu: 200m
          memory: 12G
    nginx-ingress:
      enabled: false
    nodeSelector:
      spack.io/node-pool: gitlab
    postgresql:
      install: false
    prometheus:
      install: false
    registry:
      ingress:
        tls:
          secretName: tls-gitlab-registry
      nodeSelector:
        spack.io/node-pool: gitlab
  valuesFrom:
  - secretKeyRef:
      key: values.yaml
      name: gitlab-secrets
      namespace: gitlab
      optional: false
