---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  chart:
    name: cluster-autoscaler
    repository: https://kubernetes.github.io/autoscaler
    version: 9.9.2
  releaseName: cluster-autoscaler
  values:
    autoDiscovery:
      clusterName: spack
      tags:
      - k8s.io/cluster-autoscaler/enabled
      - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}
      - kubernetes.io/cluster/{{ .Values.autoDiscovery.clusterName }}
    awsRegion: us-east-1
    cloudProvider: aws
    extraArgs:
      balance-similar-node-groups: true
      leader-elect: true
      skip-nodes-with-system-pods: false
    nodeSelector:
      spack.io/node-pool: base
    replicaCount: 3
    serviceMonitor:
      enabled: false
