---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: runner-large-arm-prot
  namespace: gitlab
spec:
  chart:
    name: gitlab-runner
    repository: https://charts.gitlab.io
    version: 0.37.2
  releaseName: large-arm-prot
  values:
    checkInterval: 30
    concurrent: 20
    gitlabUrl: https://gitlab.spack.io/
    image: gitlab/gitlab-runner:alpine-v14.7.0
    imagePullPolicy: IfNotPresent
    metrics:
      enabled: true
    nodeSelector:
      spack.io/node-pool: base
    rbac:
      serviceAccountName: runner
    replicas: 3
    runners:
      cache: {}
      config: "[[runners]]\n  output_limit = 4096\n  environment = [\"FF_GITLAB_REGISTRY_HELPER_IMAGE=1\"\
        ]\n  [runners.kubernetes]\n    helper_image = \"gitlab/gitlab-runner-helper:arm-latest\"\
        \n    privileged = false\n\n    cpu_request = \"750m\"\n    cpu_request_overwrite_max_allowed\
        \ = \"16\"\n    cpu_limit = \"16\"\n    cpu_limit_overwrite_max_allowed =\
        \ \"16\"\n\n    memory_request = \"2G\"\n    memory_request_overwrite_max_allowed\
        \ = \"64G\"\n    memory_limit = \"64G\"\n    memory_limit_overwrite_max_allowed\
        \ = \"64G\"\n\n    namespace = \"pipeline\"\n    poll_timeout = 600  # ten\
        \ minutes\n    service_account = \"runner\"\n    [runners.kubernetes.pod_annotations]\n\
        \      \"gitlab/ci_pipeline_url\" = \"$CI_PIPELINE_URL\"\n      \"gitlab/ci_job_url\"\
        \ = \"$CI_JOB_URL\"\n      \"gitlab/ci_project_url\" = \"$CI_PROJECT_URL\"\
        \n      \"gitlab/ci_runner_description\" = \"$CI_RUNNER_DESCRIPTION\"\n  \
        \    \"gitlab/ci_job_id\" = \"$CI_JOB_ID\"\n    [runners.kubernetes.pod_labels]\n\
        \      \"gitlab/ci_job_size\" = \"$CI_JOB_SIZE\"\n      \"metrics/gitlab_ci_pipeline_id\"\
        \ = \"$CI_PIPELINE_ID\"\n      \"metrics/gitlab_ci_project_namespace\" = \"\
        $CI_PROJECT_NAMESPACE\"\n      \"metrics/gitlab_ci_project_name\" = \"$CI_PROJECT_NAME\"\
        \n      \"metrics/gitlab_ci_job_stage\" = \"$CI_JOB_STAGE\"\n      \"metrics/gitlab_ci_commit_ref_name\"\
        \ = \"$CI_COMMIT_REF_NAME\"\n      \"metrics/spack_ci_stack_name\" = \"$SPACK_CI_STACK_NAME\"\
        \n      \"metrics/spack_job_spec_pkg_name\" = \"$SPACK_JOB_SPEC_PKG_NAME\"\
        \n      \"metrics/spack_spec_needs_rebuild\" = \"$SPACK_SPEC_NEEDS_REBUILD\"\
        \n    [runners.kubernetes.node_selector]\n      \"kubernetes.io/arch\" = \"\
        arm64\"\n      \"spack.io/node-pool\" = \"glr-large-pub\"\n\n    [[runners.kubernetes.volumes.secret]]\n\
        \      name = \"spack-intermediate-ci-signing-key\"\n      mount_path = \"\
        /mnt/key/\"\n      read_only = true\n"
      image: busybox:1.32.0
      imagePullPolicy: if-not-present
      locked: true
      protected: true
      runUntagged: false
      secret: spack-project-runner-registration-token
      serviceAccountName: runner
      services: {}
      tags: arm,aarch64,graviton,graviton2,small,medium,large,huge,protected,aws,spack
    terminationGracePeriodSeconds: 21600
    unregisterRunners: true
