---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: runner-xlarge-arm-pub
  namespace: gitlab
spec:
  chart:
    name: gitlab-runner
    repository: https://charts.gitlab.io
    version: 0.37.2
  releaseName: xlarge-arm-pub
  values:
    checkInterval: 30
    concurrent: 5
    gitlabUrl: https://gitlab.spack.io/
    image: gitlab/gitlab-runner:alpine-v14.7.0
    imagePullPolicy: IfNotPresent
    metrics:
      enabled: true
    nodeSelector:
      spack.io/node-pool: base
    rbac:
      serviceAccountName: runner
    runners:
      cache: {}
      config: "[[runners]]\n  requestConcurrency =  20\n  output_limit = 4096\n  environment\
        \ = [\"FF_GITLAB_REGISTRY_HELPER_IMAGE=1\"]\n  [runners.kubernetes]\n    helper_image\
        \ = \"gitlab/gitlab-runner-helper:arm-latest\"\n    privileged = false\n \
        \   cpu_request = \"9000m\"\n    namespace = \"pipeline\"\n    pollTimeout\
        \ = 600  # ten minutes\n    service_account = \"runner\"\n    [runners.kubernetes.node_selector]\n\
        \      \"kubernetes.io/arch\" = \"arm64\"\n      \"spack.io/node-pool\" =\
        \ \"glr-xlarge-pub\"\n"
      helpers:
        image: gitlab/gitlab-runner-helper:arm-latest
      image: busybox:1.32.0
      imagePullPolicy: if-not-present
      locked: false
      privileged: false
      runUntagged: false
      secret: gitlab-gitlab-runner-secret
      services: {}
      tags: arm,aarch64,graviton,graviton2,xlarge,public,aws,spack
    terminationGracePeriodSeconds: 21600
    unregisterRunners: true
