---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.0.2
  releaseName: cert-manager
  values:
    cainjector:
      enabled: true
      nodeSelector:
        spack.io/node-pool: base
      replicaCount: 3
      requests:
        cpu: 30m
        memory: 200M
    extraArgs:
    - --enable-certificate-owner-ref=true
    installCRDs: false
    nodeSelector:
      spack.io/node-pool: base
    prometheus:
      enabled: false
    replicaCount: 3
    resources:
      requests:
        cpu: 50m
        memory: 300M
    webhook:
      nodeSelector:
        spack.io/node-pool: base
      replicaCount: 3
      resources:
        requests:
          cpu: 300m
          memory: 50M
