---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 32.0.2
  releaseName: kube-prometheus-stack
  values:
    alertmanager:
      alertmanagerSpec:
        alertmanagerConfigSelector:
          matchLabels:
            alertmanagerConfig: spack
        externalUrl: https://alertmanager.spack.io
      ingress:
        enabled: false
    defaultRules:
      additionalRuleLabels:
        namespace: monitoring
        source_namespace: '{{ $labels.namespace }}'
    grafana:
      ingress:
        enabled: false
    kube-state-metrics:
      metricLabelsAllowlist:
      - pods=[metrics/gitlab_ci_commit_ref_name,metrics/gitlab_ci_job_stage,metrics/gitlab_ci_pipeline_id,metrics/gitlab_ci_project_name,metrics/gitlab_ci_project_namespace,metrics/spack_ci_stack_name,metrics/spack_job_spec_pkg_name,metrics/spack_spec_needs_rebuild]
      - nodes=[beta.kubernetes.io/instance-type,spack.io/instance-cost,spack.io/node-pool,
        spack.io/pipeline]
    namespaceOverride: monitoring
    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        externalUrl: https://prometheus.spack.io
        nodeSelector:
          spack.io/node-pool: beefy
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 200Gi
              storageClassName: gp2
