---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 32.0.2
  releaseName: kube-prometheus-stack
  values:
    alertmanager:
      alertmanagerSpec:
        alertmanagerConfigSelector:
          matchLabels:
            alertmanagerConfig: spack
        externalUrl: https://alertmanager.spack.io
      ingress:
        enabled: false
    defaultRules:
      additionalRuleLabels:
        namespace: monitoring
        source_namespace: '{{ $labels.namespace }}'
    grafana:
      ingress:
        enabled: false
    kube-state-metrics:
      metricLabelsAllowlist:
      - pods=[metrics/*]
    namespaceOverride: monitoring
    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        externalUrl: https://prometheus.spack.io
        nodeSelector:
          spack.io/node-pool: beefy
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 200Gi
              storageClassName: gp2
