---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 32.0.2
  releaseName: kube-prometheus-stack
  values:
    alertmanager:
      alertmanagerSpec:
        alertmanagerConfigSelector:
          matchLabels:
            alertmanagerConfig: spack
        externalUrl: https://alertmanager.spack.io
      ingress:
        enabled: false
    defaultRules:
      additionalRuleLabels:
        namespace: monitoring
        source_namespace: '{{ $labels.namespace }}'
    grafana:
      admin:
        existingSecret: kube-prometheus-stack-grafana
        passwordKey: admin-password
        userKey: admin-user
      envValueFrom:
        GF_AUTH_GITHUB_CLIENT_ID:
          secretKeyRef:
            key: client-id
            name: grafana-github-oauth-client
        GF_AUTH_GITHUB_CLIENT_SECRET:
          secretKeyRef:
            key: client-secret
            name: grafana-github-oauth-client
      grafana.ini:
        analytics:
          check_for_updates: true
        auth.github:
          allow_sign_up: true
          allowed_organizations: spack
          api_url: https://api.github.com/user
          auth_url: https://github.com/login/oauth/authorize
          client_id: DEADBEEF
          client_secret: DEADBEEF
          enabled: true
          scopes: user:email,read:org
          token_url: https://github.com/login/oauth/access_token
        grafana_net:
          url: https://grafana.net
        log:
          mode: console
        paths:
          data: /var/lib/grafana/
          logs: /var/log/grafana
          plugins: /var/lib/grafana/plugins
          provisioning: /etc/grafana/provisioning
        server:
          root_url: https://grafana.spack.io
      ingress:
        enabled: false
    kube-state-metrics:
      metricLabelsAllowlist:
      - pods=[metrics/gitlab_ci_commit_ref_name,metrics/gitlab_ci_job_stage,metrics/gitlab_ci_pipeline_id,metrics/gitlab_ci_project_name,metrics/gitlab_ci_project_namespace,metrics/spack_ci_stack_name,metrics/spack_job_spec_pkg_name,metrics/spack_spec_needs_rebuild]
      - nodes=[beta.kubernetes.io/instance-type,spack.io/instance-cost,spack.io/node-pool,
        spack.io/pipeline]
    namespaceOverride: monitoring
    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        externalUrl: https://prometheus.spack.io
        nodeSelector:
          spack.io/node-pool: beefy
        resources:
          requests:
            cpu: 2000m
            memory: 50G
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 200Gi
              storageClassName: gp2
    prometheusOperator:
      resources:
        requests:
          cpu: 750m
          memory: 300M
