---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alertmanagerConfig: spack
  name: alertmanager-config
  namespace: monitoring
spec:
  receivers:
  - name: slack
    slackConfigs:
    - apiURL:
        key: webhook
        name: slack-webhook-alertmanager
      channel: '#monitoring-alerts'
      iconEmoji: ':warning:'
      text: '{{ .CommonAnnotations.description }}

        {{ range .Alerts }}

        *{{.Labels.alertname}}* ({{ .Fingerprint }}): <{{ .GeneratorURL }}|:chart_with_upwards_trend:>

        {{.Annotations.description}}


        {{ end }}'
      title: '[{{ .CommonLabels.severity }}] {{ .GroupLabels.alertname }} ({{ .Alerts.Firing
        | len }}) - {{ .CommonAnnotations.summary }}'
  route:
    groupBy:
    - alertname
    groupInterval: 5m
    groupWait: 30s
    receiver: slack
    repeatInterval: 12h
