---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
  name: kube-prometheus-stack-spack-custom-alerts
  namespace: monitoring
spec:
  groups:
  - name: spack-custom-alerts
    rules:
    - alert: GitlabPipelinePodStuck
      annotations:
        description: '{{ $labels.pod }} has had no activity for more than 5 minutes.'
        runbook_url: TODO
        summary: The pod appears to be stuck.  No CPU, RAM, or Network activity for
          the last 5 minutes.
      expr: node_namespace_pod_name:pipeline_stuck_pods_info == 1
      for: 5m
      labels:
        namespace: monitoring
        severity: critical
        source_namespace: '{{ $labels.namespace }}'
