---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alertmanagerConfig: spack
  name: alertmanager-config
  namespace: monitoring
spec:
  receivers:
  - name: slack
    slackConfigs:
    - apiURL:
        key: webhook
        name: slack-webhook-alertmanager
      channel: '#monitoring-alerts'
      sendResolved: true
      text: "{{ range .Alerts }}\n    *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity\
        \ }}`\n    *Description:* {{ .Annotations.description }}\n    *Graph:* <{{\
        \ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook\
        \ }}|:spiral_note_pad:>\n    *Details:*\n        {{ range .Labels.SortedPairs\
        \ }} \u2022 *{{ .Name }}:* `{{ .Value }}`\n        {{ end }}\n{{ end }}"
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
        | len }}{{ end }}] Monitoring Event Notification'
  route:
    groupBy:
    - job
    groupInterval: 5m
    groupWait: 30s
    receiver: slack
    repeatInterval: 12h
