---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/exec
  - secrets
  - configmaps
  - pods/attach
  verbs:
  - get
  - watch
  - list
  - update
  - create
  - patch
  - delete
